version: "3.8"

services:
  mssql:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    env_file:
      - sqlserver.env
    ports:
      - 1433:1433
    networks:
      - streetcode

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"  
    env_file:
      - mongodb.env
    restart: always

  streetcode.webapi:
    image: ${DOCKER_REGISTRY-}streetcodewebapi
    build:
      context: .
      dockerfile: Streetcode.WebApi/Dockerfile
    ports:
      - 8001:80
    hostname: street-code-api
    networks:
      - streetcode

  userservice.webapi:
    image: ${DOCKER_REGISTRY-}userservicewebapi
    build:
      context: .
      dockerfile: UserService.WebApi/Dockerfile
    ports:
      - 8002:80
    hostname: streetcode-user-api
    networks:
      - streetcode

networks:
  streetcode:
    driver: bridge
