name: Run Unit Tests
on:
  push:
    branches: [main, dev, enhancement/SSAD-218/implement-pipeline-to-run-unit-tests-on-pushmerge-to-maindev-branch]
  pull_request:
    branches: [main, dev]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'
      
      - name: Run tests
        run: |
          testProjects=$(find . -type f \( -name "*Test.csproj" -o -name "*Tests.csproj" \))
          if [ -z "$testProjects" ]; then
            echo "No test projects found"
            exit 1
          fi
          echo "Found test projects:"
          echo "$testProjects"
          echo "Running tests..."
          # Перебор файлов
          for project in $testProjects; do
            echo "Testing $project"
            dotnet test "$project"
          done

