name: Unit Testing

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
    types:
      - opened
      - synchronize
      - reopened
   

jobs:
  test-all:
    name: Build and Test All Projects
    runs-on: ubuntu-latest
    env:
      SOLUTION_PATH: 'Streetcode\Streetcode.sln'
      BUILD_CONFIG: 'Release'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'

      - name: Restore Dependencies
        run: dotnet restore ./Streetcode/Streetcode.sln

      - name: Build
        run: dotnet build ./Streetcode/Streetcode.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test $env:SOLUTION_PATH --configuration $env:BUILD_CONFIG --no-build --verbosity normal --logger "trx;LogFileName=test-res.trx" || true
      - name: Create-Testing-Result-Report
        uses: phoenix-actions/test-reporting@v8      
        if: success() || failure()
        id: test-report
        with:
          name: Test-Results
          reporter: dotnet-trx
          path: "**/test-res.trx"        
          fail-on-error: true
