name: Unit Testing

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
    types:
      - opened
      - synchronize
      - reopened
   

jobs:
  test-all:
    name: Build and Test All Projects
    runs-on: ubuntu-latest
    env:
      SOLUTION_PATH: 'Streetcode\Streetcode.sln'
      BUILD_CONFIG: 'Release'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'

      - name: Restore Dependencies
        run: dotnet restore ./Streetcode/Streetcode.sln

      - name: Build
        run: dotnet build ./Streetcode/Streetcode.sln --configuration Release --no-restore

      - name: Run tests
        run: |
          # Find all .csproj with tests and run them
          testProjects=$(find . -type f \( -name "*Test.csproj" -o -name "*Tests.csproj" \))
          if [ -z "$testProjects" ]; then
            echo "No test projects found"
            exit 1
          fi
          echo "Found test projects:"
          echo "$testProjects"
          echo "Running tests..."
          for project in $testProjects; do
            echo "Testing $project"
            dotnet test "$project" --configuration Release
          done
