name: Run Unit Tests for All Projects

on:
  push:
    branches:
      - main
      - dev
      - enhancement/SSAD-218/implement-pipeline-to-run-unit-tests-on-pushmerge-to-maindev-branch
  pull_request:
    branches:
      - main
      - dev

jobs:
  test-all:
    name: Build and Test All Projects
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0' 

      - name: Build
        run: |
          for testProject in $(find . -name "*Test.csproj"); do
              dotnet build "$testProject"
            done
        
      - name: Find and run tests
        run: |
          testProjects=$(find . -type f -name "*Test.csproj" -o -name "*Tests.csproj")
          if [ -z "$testProjects" ]; then
            echo "No test projects found"
            exit 1
          fi
          echo "Found test projects:"
          echo "$testProjects"
          echo "Running tests..."
          for project in $testProjects; do
            echo "Testing $project"
            dotnet test "$project"
          done
